
project_id = "tlpjehaznykckdtdjwff"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.domain-search]
verify_jwt = true

[functions.whois-lookup]
verify_jwt = true
