// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlpjehaznykckdtdjwff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscGplaGF6bnlrY2tkdGRqd2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjcxMjcsImV4cCI6MjA2MjEwMzEyN30.I8_BNJ9PpmvuZnryZ4P4uYFZNOKWr9bYiSs5VsPBKks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);